import { Geist, Geist_Mono } from "next/font/google";
import imgMeta from "../component/image/metaimage.jpg";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); 

export const metadata = {
  title:"Screenshot Viewer & Sharing App",
   description: "Generated by create next app. View screenshots and share them with friends.",
    openGraph: {
    title: "Screenshot Viewer & Sharing App",
    description: "View screenshots and share them with friends.",
    url: "https://your-domain.com",
    siteName: "Screenshot App",
    images: [
      {
        url: imgMeta, // картинка в папке public/
        width: 1200,
        height: 630,
        alt: "Screenshot preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Screenshot Viewer & Sharing App",
    description: "View screenshots and share them with friends.",
    images: [imgMeta], // та же картинка
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
